FROM python:3.12-slim

WORKDIR /app

COPY botfactory/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY botfactory/ .
COPY api/ api/
COPY core/ core/

VOLUME /data

EXPOSE 9000

CMD ["python", "main.py"]
